agent_right:
  port: /dev/ttyUSB0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [1.5708, 1.5708, 3.14159, 3.14159, 1.5708, 1.5708]
    joint_signs: [1.0, -1.0, 1.0, 1.0, 1.0, 1.0]
    gripper_config: [7, 176.662109375, 236.162109375]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
agent_left:
  port: /dev/ttyUSB1
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [4.71239, 4.71239, 3.14159, 6.28319, 1.5708, 4.71239]
    joint_signs: [1.0, -1.0, 1.0, 1.0, 1.0, 1.0]
    gripper_config: [7, 86.486328125, 145.986328125]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]